# Generated by Django 2.2.7 on 2020-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
