# Generated by Django 2.2.7 on 2020-08-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.CharField(blank='True', max_length=1000, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='gmail_url',
            field=models.CharField(blank='True', max_length=1000, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.CharField(blank='True', max_length=1000, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank='True', null='True', upload_to='images/profile'),
            preserve_default='True',
        ),
    ]
